/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RiskAssessmentRouteImport } from './routes/risk-assessment'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KycRouteImport } from './routes/kyc'
import { Route as InvestmentsRouteImport } from './routes/investments'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdvisoryRouteImport } from './routes/advisory'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiVerifyOtpRouteImport } from './routes/api/verify-otp'
import { Route as ApiSendOtpRouteImport } from './routes/api/send-otp'

const RiskAssessmentRoute = RiskAssessmentRouteImport.update({
  id: '/risk-assessment',
  path: '/risk-assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KycRoute = KycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentsRoute = InvestmentsRouteImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisoryRoute = AdvisoryRouteImport.update({
  id: '/advisory',
  path: '/advisory',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerifyOtpRoute = ApiVerifyOtpRouteImport.update({
  id: '/api/verify-otp',
  path: '/api/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendOtpRoute = ApiSendOtpRouteImport.update({
  id: '/api/send-otp',
  path: '/api/send-otp',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advisory': typeof AdvisoryRoute
  '/blog': typeof BlogRoute
  '/dashboard': typeof DashboardRoute
  '/investments': typeof InvestmentsRoute
  '/kyc': typeof KycRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/risk-assessment': typeof RiskAssessmentRoute
  '/api/send-otp': typeof ApiSendOtpRoute
  '/api/verify-otp': typeof ApiVerifyOtpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advisory': typeof AdvisoryRoute
  '/blog': typeof BlogRoute
  '/dashboard': typeof DashboardRoute
  '/investments': typeof InvestmentsRoute
  '/kyc': typeof KycRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/risk-assessment': typeof RiskAssessmentRoute
  '/api/send-otp': typeof ApiSendOtpRoute
  '/api/verify-otp': typeof ApiVerifyOtpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advisory': typeof AdvisoryRoute
  '/blog': typeof BlogRoute
  '/dashboard': typeof DashboardRoute
  '/investments': typeof InvestmentsRoute
  '/kyc': typeof KycRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/risk-assessment': typeof RiskAssessmentRoute
  '/api/send-otp': typeof ApiSendOtpRoute
  '/api/verify-otp': typeof ApiVerifyOtpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advisory'
    | '/blog'
    | '/dashboard'
    | '/investments'
    | '/kyc'
    | '/login'
    | '/pricing'
    | '/register'
    | '/risk-assessment'
    | '/api/send-otp'
    | '/api/verify-otp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advisory'
    | '/blog'
    | '/dashboard'
    | '/investments'
    | '/kyc'
    | '/login'
    | '/pricing'
    | '/register'
    | '/risk-assessment'
    | '/api/send-otp'
    | '/api/verify-otp'
  id:
    | '__root__'
    | '/'
    | '/advisory'
    | '/blog'
    | '/dashboard'
    | '/investments'
    | '/kyc'
    | '/login'
    | '/pricing'
    | '/register'
    | '/risk-assessment'
    | '/api/send-otp'
    | '/api/verify-otp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvisoryRoute: typeof AdvisoryRoute
  BlogRoute: typeof BlogRoute
  DashboardRoute: typeof DashboardRoute
  InvestmentsRoute: typeof InvestmentsRoute
  KycRoute: typeof KycRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  RegisterRoute: typeof RegisterRoute
  RiskAssessmentRoute: typeof RiskAssessmentRoute
  ApiSendOtpRoute: typeof ApiSendOtpRoute
  ApiVerifyOtpRoute: typeof ApiVerifyOtpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/risk-assessment': {
      id: '/risk-assessment'
      path: '/risk-assessment'
      fullPath: '/risk-assessment'
      preLoaderRoute: typeof RiskAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kyc': {
      id: '/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof KycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investments': {
      id: '/investments'
      path: '/investments'
      fullPath: '/investments'
      preLoaderRoute: typeof InvestmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisory': {
      id: '/advisory'
      path: '/advisory'
      fullPath: '/advisory'
      preLoaderRoute: typeof AdvisoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verify-otp': {
      id: '/api/verify-otp'
      path: '/api/verify-otp'
      fullPath: '/api/verify-otp'
      preLoaderRoute: typeof ApiVerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-otp': {
      id: '/api/send-otp'
      path: '/api/send-otp'
      fullPath: '/api/send-otp'
      preLoaderRoute: typeof ApiSendOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvisoryRoute: AdvisoryRoute,
  BlogRoute: BlogRoute,
  DashboardRoute: DashboardRoute,
  InvestmentsRoute: InvestmentsRoute,
  KycRoute: KycRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  RegisterRoute: RegisterRoute,
  RiskAssessmentRoute: RiskAssessmentRoute,
  ApiSendOtpRoute: ApiSendOtpRoute,
  ApiVerifyOtpRoute: ApiVerifyOtpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
